### ISSUE TITLE
Routes with parameters

### ISSUE THREAD

**Issue by jobezic** [blairmotchan/ngRoleSecurity#1]
It does not work on route with parameters, like /customer/:id.. it seems that it ignores the parameter and it redirects to forbidden route :(

**Comment by blairmotchan** [comment]
Thank you very much for identifying this issue and for your pull request.  I'll be able to to integrate it into the code base shortly.

**Comment by blairmotchan** [comment]
Please see my comments to your pull request.  I'll be able to push this fix out tomorrow night probably with test updates as well.

Thank you very much for your help

**Comment by blairmotchan** [comment]
Doing something like this would solve the issues that I pointed out:

```
  $rootScope.$evalAsync(function () {
    angular.forEach(next.pathParams, function(paramValue, pathParam) {
       path = path.replace(new RegExp(':' + pathParam + '(/|$)'), paramValue + '$1');
     });
     location.path(path);
  });
```

So, like I said, what you provided was very, very close and it definitely helped me get this fixed much sooner.

**Comment by blairmotchan** [comment]
Please see tag  2.0.2

Thanks again pinkra for pointing this out and for your help.

**Comment by jobezic** [comment]
Good! You are welcome!
